version: '2'
services:
  telegrambot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: irkbot-telegram
    volumes:
      - ./html/screenshots:/app/html/screenshots
      - ./log/bot:/app/log/bot

  nginx:
    image: nginx:alpine
    ports:
      - "5784:80"
    restart: always
    container_name: irkbot-nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./log/nginx:/var/log/nginx
